name: Release container image

on:
  push:
    branches:
      - master

jobs:
  #
  # Job: cancel
  #
  cancel:
    name: "Cancel previous workflow runs"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          workflow_id: release.yaml
          access_token: ${{ github.token }}

  #
  # Job: tests
  #
  tests:
    name: "Run tests"
    needs:
      - cancel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run tests
        shell: bash
        run: |
          make build
          make test

  #
  # Job: build_info
  #
  build_info:
    name: "Gather information about the build"
    needs:
      - tests
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build_info.outputs.version }}
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Determine image version
        id: build_info
        shell: bash
        run: |
          set -ueo pipefail

          make build

          version="$(make version)"
          echo "::debug::Setting version to ${version}"
          echo "::set-output name=version::${version}"

  #
  # Job: build_container_image
  #
  build_container_image:
    needs:
      - build_info
    name: "Build and publish container image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ needs.build_info.outputs.version }}
