name: Update dependencies

on: workflow_dispatch

jobs:
  up:
    name: mod up
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: variantdev/mod-action@v0.21.1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        args: up --build --pull-request
